apiVersion : apps/v1
kind: Deployment
metadata:
  name: usermanagementcicd
  namespace: user-management 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementcicd
  template:
    metadata:
      labels:
        app: usermanagementcicd 
    spec:
      containers:
        - name: usermanagementcicd 
          image: acrusermanagementcicd.azurecr.io/usermanagementcicd
          ports:
          - containerPort: 80