apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - name: frontend-deployment
          image: crusermanagement.azurecr.io/usermanagement-ui-i:latest
          ports:
            - containerPort: 80