apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: debasisnandiusermanagementcicd 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: debasisnandiusermanagementcicd 
    spec:
      containers:
        - name: debasisnandiusermanagementcicd 
          image: acrusermanagementcicd.azurecr.io/debasisnandiusermanagementcicd
          ports:
          - containerPort: 80