apiVersion : apps/v1
kind: Deployment
metadata:
  name: usermanagementui
  namespace: user-management 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagementui
  template:
    metadata:
      labels:
        app: usermanagementui 
    spec:
      containers:
        - name: usermanagementui 
          image: acrusermanagement.azurecr.io/acrusermanagement
          ports:
          - containerPort: 80