apiVersion: v1
kind: Service
metadata:
    name: usermanagementcicd-service
    namespace: user-management
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: usermanagementcicd